"""
ML surrogate + inverse design.

Two jobs, both mirroring the honest split LockBench is built on:

  * **Surrogate** — a model that maps a design (loop bandwidth, phase-margin target, Icp,
    N, Kvco) to its *worst-case-across-PVT* metrics (phase margin, lock time, jitter
    peaking), so you get an instant estimate without sweeping corners. Its training rows
    are generated by the linear PLL model (fast, exact for the model); the model just
    learns to interpolate them cheaply.
  * **Inverse design** — given target specs, scan the surrogate over a grid in
    milliseconds and hand back the most promising design point (whose exact R/C then come
    from the analytical designer).

The *grounding* is still the real datasheet library; the ML only accelerates search over
the model. That distinction is stated plainly so the tool survives scrutiny.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .devices import Device, load_devices, get_device
from .design import design_pll, divider_for_output
from .robust import PLLSpec, CornerSpec, robust_evaluate

# Feature order is fixed and shared by training and inference.
FEATURES = ["log10_fc_hz", "pm_target_deg", "log10_icp_a", "log10_n", "log10_kvco_hz"]
LABELS = ["worst_phase_margin_deg", "log10_worst_lock_time_s", "worst_jitter_peaking_db"]

_DEFAULT_CORNER = CornerSpec(kvco_tol=0.30, icp_tol=0.10)


def _features(fc_hz: float, pm_deg: float, icp_a: float, n: float, kvco_hz: float) -> list[float]:
    return [
        float(np.log10(fc_hz)),
        float(pm_deg),
        float(np.log10(icp_a)),
        float(np.log10(n)),
        float(np.log10(kvco_hz)),
    ]


# ------------------------------------------------------------------ dataset

def make_dataset(n_samples: int = 1200, seed: int = 0,
                 corner_spec: CornerSpec = _DEFAULT_CORNER) -> tuple[np.ndarray, np.ndarray]:
    """Sample random valid designs across the real device library and label them with
    worst-case-across-PVT metrics. Returns (X, Y) arrays."""
    rng = np.random.default_rng(seed)
    devices = load_devices()
    X, Y = [], []
    attempts = 0
    while len(X) < n_samples and attempts < n_samples * 6:
        attempts += 1
        dev = devices[rng.integers(len(devices))]
        # A phase-detector frequency the part supports, and an output in its VCO range.
        f_pfd = float(rng.uniform(0.2, 1.0) * dev.pfd_max_hz)
        f_out = float(rng.uniform(dev.vco_min_hz, dev.vco_max_hz))
        n = f_out / f_pfd
        if not (dev.n_min <= n <= dev.n_max):
            continue
        fc = float(rng.uniform(f_pfd / 60.0, f_pfd / 8.0))       # sane loop bandwidth
        pm = float(rng.uniform(40.0, 65.0))
        icp = float(dev.icp_options_a[rng.integers(len(dev.icp_options_a))])
        kvco = dev.kvco_rad_per_v
        try:
            pll = design_pll(dev, n=n, fc_hz=fc, phase_margin_deg=pm, icp_a=icp)
            report = robust_evaluate(pll, PLLSpec(), corner_spec)
        except Exception:
            continue
        w = report.worst
        if not (np.isfinite(w["min_phase_margin_deg"]) and np.isfinite(w["max_lock_time_s"])
                and w["max_lock_time_s"] > 0):
            continue
        X.append(_features(fc, pm, icp, n, dev.kvco_hz_per_v))
        Y.append([
            w["min_phase_margin_deg"],
            float(np.log10(w["max_lock_time_s"])),
            w["max_jitter_peaking_db"],
        ])
    return np.asarray(X, float), np.asarray(Y, float)


# ------------------------------------------------------------------ train / load

def train(X: np.ndarray, Y: np.ndarray):
    """Fit a multi-output random-forest surrogate. Returns (model, r2_per_label)."""
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import r2_score

    Xtr, Xte, Ytr, Yte = train_test_split(X, Y, test_size=0.2, random_state=0)
    model = RandomForestRegressor(n_estimators=200, max_depth=None,
                                  min_samples_leaf=2, random_state=0, n_jobs=-1)
    model.fit(Xtr, Ytr)
    r2 = r2_score(Yte, model.predict(Xte), multioutput="raw_values")
    return model, {lbl: float(s) for lbl, s in zip(LABELS, r2)}


def save(model, path: Path) -> None:
    import joblib
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    joblib.dump({"model": model, "features": FEATURES, "labels": LABELS}, path)


def load_surrogate(path: Path):
    import joblib
    return joblib.load(path)


# ------------------------------------------------------------------ inference

def predict_metrics(bundle, fc_hz: float, pm_deg: float, icp_a: float,
                    n: float, kvco_hz: float) -> dict:
    """Instant surrogate estimate of the worst-case-across-PVT metrics."""
    x = np.asarray([_features(fc_hz, pm_deg, icp_a, n, kvco_hz)], float)
    y = bundle["model"].predict(x)[0]
    return {
        "worst_phase_margin_deg": float(y[0]),
        "worst_lock_time_s": float(10.0 ** y[1]),
        "worst_jitter_peaking_db": float(y[2]),
    }


@dataclass
class Recommendation:
    fc_hz: float
    phase_margin_deg: float
    icp_a: float
    predicted: dict


def recommend_design(bundle, device: Device, n: float, spec: PLLSpec,
                     f_pfd_hz: float) -> Recommendation | None:
    """Inverse design: scan the surrogate over a grid and return the best design point
    predicted to meet the spec (fastest predicted lock time among predicted-passing).

    The whole grid is scored in a single batched forest prediction, so this returns in
    milliseconds regardless of grid size.
    """
    fc_grid = np.logspace(np.log10(f_pfd_hz / 60.0), np.log10(f_pfd_hz / 8.0), 20)
    pm_grid = np.array([45.0, 48.0, 50.0, 53.0, 56.0, 60.0])
    icp_grid = np.array(device.icp_options_a)
    kvco_hz = device.kvco_hz_per_v

    # Cartesian product of the grid -> one feature matrix -> one predict call.
    FC, PM, ICP = np.meshgrid(fc_grid, pm_grid, icp_grid, indexing="ij")
    fc = FC.ravel(); pm = PM.ravel(); icp = ICP.ravel()
    X = np.column_stack([
        np.log10(fc), pm, np.log10(icp),
        np.full(fc.shape, np.log10(n)), np.full(fc.shape, np.log10(kvco_hz)),
    ])
    Y = bundle["model"].predict(X)
    worst_pm = Y[:, 0]
    worst_lock = 10.0 ** Y[:, 1]
    worst_peak = Y[:, 2]

    ok = worst_pm >= spec.min_phase_margin_deg
    if spec.max_jitter_peaking_db is not None:
        ok &= worst_peak <= spec.max_jitter_peaking_db
    if spec.max_lock_time_s is not None:
        ok &= worst_lock <= spec.max_lock_time_s
    if not np.any(ok):
        return None

    idx_ok = np.nonzero(ok)[0]
    best = idx_ok[np.argmin(worst_lock[idx_ok])]   # fastest predicted lock among passing
    return Recommendation(
        fc_hz=float(fc[best]), phase_margin_deg=float(pm[best]), icp_a=float(icp[best]),
        predicted={
            "worst_phase_margin_deg": float(worst_pm[best]),
            "worst_lock_time_s": float(worst_lock[best]),
            "worst_jitter_peaking_db": float(worst_peak[best]),
        },
    )
